apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-redhat

helmCharts:
- name: operators-installer
  version: 2.4.1
  repo: https://redhat-cop.github.io/helm-charts
  valuesFile: values.yaml
  namespace: openshift-operators-redhat