approveManualInstallPlanViaHook: true

# Image to use for the InstallPlan Approver and Verify Jobs
installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli:v4.10@sha256:7804ea66ea8ca0f414148b8b3b52ae454800785e80a32bd8a5eb2db789014a00

# EXAMPLE: declaratively controlled operator version
operators:
 - channel: stable-5.8
   installPlanApproval: Manual
   name: loki-operator
   source: redhat-operators
   sourceNamespace: openshift-marketplace
   csv: loki-operator.v5.8.1
   namespace: openshift-operators-redhat

# configuration for control of OperatorGroups
operatorGroups:
# EXAMPLE: adding OperatorGroup to named namespace
 - name: openshift-operators-redhat
   createNamespace: true

# EXAMPLE: adding OperatorGroup to Helm .Release.Namespace
# - createNamespace:
#   targetOwnNamespace:
#   otherTargetNamespaces:

# Common labels to add to all chart created resources.
# Implements the same idea from Kustomize for this chart.
#commonLabels:
