---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-secrets
  namespace: openshift-logging
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-create-secrets
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-secrets-sa
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-secrets
subjects:
- kind: ServiceAccount
  name: job-create-secrets
---
# create one installplan-approver job per manual operator
apiVersion: batch/v1
kind: Job
metadata:
  name: job-generate-secret
  namespace: openshift-logging
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  activeDeadlineSeconds: 240
  template:
    spec:
      containers:
      - name: secret-creation
        image: registry.redhat.io/openshift4/ose-cli:v4.13
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            echo "Starting..."

            echo "Retrieving CM data"
            BUCKET_HOST=$(oc get -n openshift-logging configmap logging-loki-s3 -o jsonpath='{.data.BUCKET_HOST}')
            BUCKET_NAME=$(oc get -n openshift-logging configmap logging-loki-s3 -o jsonpath='{.data.BUCKET_NAME}')
            BUCKET_PORT=$(oc get -n openshift-logging configmap logging-loki-s3 -o jsonpath='{.data.BUCKET_PORT}')

            echo "Retrieving Secret data"
            ACCESS_KEY_ID=$(oc get -n openshift-logging secret logging-loki-s3 -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
            SECRET_ACCESS_KEY=$(oc get -n openshift-logging secret logging-loki-s3 -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)

            echo "Create secret"
            oc create -n openshift-logging secret generic logging-loki-s3-secret \
            -v 3 \
            --save-config \
            --from-literal=access_key_id="${ACCESS_KEY_ID}" \
            --from-literal=access_key_secret="${SECRET_ACCESS_KEY}" \
            --from-literal=bucketnames="${BUCKET_NAME}" \
            --from-literal=endpoint="https://${BUCKET_HOST}:${BUCKET_PORT}" \
            --dry-run=client -o yaml | oc -n openshift-logging apply -f-
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: job-create-secrets
      serviceAccountName: job-create-secrets
      terminationGracePeriodSeconds: 30
...