---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-secrets
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-pull-secret-acm-observability
  namespace: open-cluster-management-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-secrets-job-acm-observability
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-secrets
subjects:
- kind: ServiceAccount
  name: job-pull-secret-acm-observability
  namespace: open-cluster-management-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-pull-secrets
  namespace: open-cluster-management-observability
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secrets-job-acm-observability
  namespace: open-cluster-management-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-pull-secrets
subjects:
- kind: ServiceAccount
  name: job-pull-secret-acm-observability
  namespace: open-cluster-management-observability
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-generate-pull-secret
  namespace: open-cluster-management-observability
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  activeDeadlineSeconds: 240
  template:
    spec:
      containers:
      - name: pull-secret-creation
        image: registry.redhat.io/openshift4/ose-cli:v4.13
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            echo "Starting..."

            echo "Retrieve pull secret"
            DOCKER_CONFIG_JSON=$(oc extract secret/pull-secret -n openshift-config --to=-)

            echo "Create pull-secret"
            oc create secret generic multiclusterhub-operator-pull-secret \
            -n open-cluster-management-observability \
            --from-literal=.dockerconfigjson="$DOCKER_CONFIG_JSON" \
            --type=kubernetes.io/dockerconfigjson

      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: job-pull-secret-acm-observability
      serviceAccountName: job-pull-secret-acm-observability
      terminationGracePeriodSeconds: 30
...