---
# https://github.com/argoproj/argo-cd/discussions/12278#discussioncomment-4863196
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd-avp-gitops
data:
  avp.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "! test -f kustomization.yaml && ! test -f Chart.yaml"
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - --verbose-sensitive-output
          - "."
      lockRepo: false
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "test -f kustomization.yaml"
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build --enable-helm . | argocd-vault-plugin generate --verbose-sensitive-output -"
      lockRepo: false
  avp-k-nodisco.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp-k-nodisco
    spec:
      allowConcurrency: true
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build --enable-helm . | argocd-vault-plugin generate --verbose-sensitive-output -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "! test -f kustomization.yaml && test -f Chart.yaml"
      generate:
        command:
          - sh
          - "-c"
          - "helm template $ARGOCD_APP_NAME --include-crds . | argocd-vault-plugin generate --verbose-sensitive-output -"
      lockRepo: false
